{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.externalSecrets.postgresSecretName }}
      property: password
{{- end }}
