# PostgreSQL Credentials Secret
# In production, use external secret management (AWS Secrets Manager, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: voting
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
