{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: postgresql-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.externalSecrets.postgresql.remoteSecretName }}
      property: password
{{- end }}
