apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandard }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandard }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandard }}