# Namespace with Pod Security Standards (restricted)
apiVersion: v1
kind: Namespace
metadata:
  name: voting
  labels:
    name: voting
    # Enforce restricted Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
